import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { Button } from './button'; // Adjust path as necessary

describe('Button component', () => {
  test('renders with children', () => {
    render(<Button>Click Me</Button>);
    const buttonElement = screen.getByText(/click me/i);
    expect(buttonElement).toBeInTheDocument();
  });

  test('applies default variant and size classes', () => {
    render(<Button>Default Button</Button>);
    const buttonElement = screen.getByText(/default button/i);
    // Example: Check for a class that should be present in the default variant
    // This depends on the actual classes generated by cva
    // For a more robust test, you might need to inspect computed styles or use a snapshot
    expect(buttonElement).toHaveClass('bg-primary'); // Assuming default variant has 'bg-primary'
  });

  test('handles onClick event', () => {
    const handleClick = jest.fn();
    render(<Button onClick={handleClick}>Clickable</Button>);
    const buttonElement = screen.getByText(/clickable/i);
    fireEvent.click(buttonElement);
    expect(handleClick).toHaveBeenCalledTimes(1);
  });

  test('renders as a different element when asChild is true', () => {
    render(
      <Button asChild>
        <div>Div Button</div>
      </Button>
    );
    // Check if it renders as a div element
    const divElement = screen.getByText(/div button/i);
    expect(divElement).toBeInTheDocument();
    expect(divElement.tagName).toBe('DIV');
  });

  test('is disabled when disabled prop is true', () => {
    render(<Button disabled>Disabled Button</Button>);
    const buttonElement = screen.getByText(/disabled button/i);
    expect(buttonElement).toBeDisabled();
  });
}); 